export const INPUT_AUTH = "INPUT_AUTH"
export const OUTPUT_AUTH = "OUTPUT_AUTH"

export const OPEN_CLOSE_MODAL_AUTH = "OPEN_CLOSE_MODAL_AUTH"
export const OPEN_CLOSE_MODAL_PHOTO = "OPEN_CLOSE_MODAL_PHOTO"

export const SET_DATA = "SET_DATA"

export const SET_FULL_PROFILE = "SET_FULL_PROFILE"
export const SET_DISPLAY_NAME = "SET_DISPLAY_NAME"
export const SET_PHONE_NUMBER = "SET_PHONE_NUMBER"
export const SET_PHOTO_URL = "SET_PHOTO_URL"